on:
  - push
jobs:
  check-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: ajlekcahdp4-llvm-bleach-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64
      - run: nix run nixpkgs#just check
